#!/bin/bash
echo "Starting daemon.."
ext_ip=$(curl ident.me)

while true; do
	cpu_usage=$((grep 'cpu ' /proc/stat;sleep 5;grep 'cpu ' /proc/stat) \
		| awk -v RS="" '{print ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)}' \
		| awk '{gsub(",","."); print $0}')
	memory_usage=$(awk '/MemTotal/{t=$2}/MemAvailable/{a=$2}END{print 100-100*a/t}' /proc/meminfo \
		| awk '{gsub(",","."); print $0}')
	disk_used=$(df | awk '/ \/$/{print $3}')
	disk_available=$(df | awk '/ \/$/{print $4}')
	curl -X POST -H 'Content-type: application/json' \
		--data "{\"ip\": \"${ext_ip}\", \"cpu\": ${cpu_usage}, \"memory\": ${memory_usage}, \"disk_used\": ${disk_used}, \"disk_available\": ${disk_available}}" \
		http://207.154.248.55:8080/api/stat
done